// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tuYYL4LS2Mqra35JfVEDDQ
// Component: csngSC__Aa
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import ChatListItem from "../../ChatListItem"; // plasmic-import: M28hjAiCwM/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_chat_app.module.css"; // plasmic-import: tuYYL4LS2Mqra35JfVEDDQ/projectcss
import sty from "./PlasmicChatList.module.css"; // plasmic-import: csngSC__Aa/css

export type PlasmicChatList__VariantMembers = {};
export type PlasmicChatList__VariantsArgs = {};
type VariantPropType = keyof PlasmicChatList__VariantsArgs;
export const PlasmicChatList__VariantProps = new Array<VariantPropType>();

export type PlasmicChatList__ArgsType = {};
type ArgPropType = keyof PlasmicChatList__ArgsType;
export const PlasmicChatList__ArgProps = new Array<ArgPropType>();

export type PlasmicChatList__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultChatListProps {
  className?: string;
}

function PlasmicChatList__RenderFunc(props: {
  variants: PlasmicChatList__VariantsArgs;
  args: PlasmicChatList__ArgsType;
  overrides: PlasmicChatList__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <ChatListItem
        className={classNames("__wab_instance", sty.chatListItem__jc0M)}
      />

      <ChatListItem
        className={classNames("__wab_instance", sty.chatListItem__wl7M)}
      />

      <ChatListItem
        className={classNames("__wab_instance", sty.chatListItem__xMFd6)}
      />

      <ChatListItem
        className={classNames("__wab_instance", sty.chatListItem__hk7Mv)}
      />
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicChatList__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicChatList__VariantsArgs;
    args?: PlasmicChatList__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicChatList__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicChatList__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicChatList__ArgProps,
          internalVariantPropNames: PlasmicChatList__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicChatList__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicChatList";
  } else {
    func.displayName = `PlasmicChatList.${nodeName}`;
  }
  return func;
}

export const PlasmicChatList = Object.assign(
  // Top-level PlasmicChatList renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicChatList
    internalVariantProps: PlasmicChatList__VariantProps,
    internalArgProps: PlasmicChatList__ArgProps
  }
);

export default PlasmicChatList;
/* prettier-ignore-end */
