// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/host";

import { ScreenVariantProvider } from "../../components/plasmic/chat_app/PlasmicGlobalVariant__Screen";
import { PlasmicRoomChat } from "../../components/plasmic/chat_app/PlasmicRoomChat";
import { useRouter } from "next/router";
import Chat from "../../components/Chat";

function RoomChat() {
  const router = useRouter()
  const {roomId} = router.query
  return (
    <ph.PageParamsProvider
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <PlasmicRoomChat
        layout={{
          mainContent: <Chat roomId={roomId} />
        }}
      
      />
    </ph.PageParamsProvider>
  );
}

export default RoomChat;
